import Config

data_dir =
  (System.get_env("KAKEMONO_DATA_DIR") ||
     Path.expand("../data/dev", __DIR__))
  |> Path.expand()

database_path = System.get_env("DATABASE_PATH") || Path.join(data_dir, "kakemono_dev.db")

File.mkdir_p!(Path.dirname(database_path))

config :kakemono,
  data_dir: data_dir,
  uploads_dir: System.get_env("KAKEMONO_UPLOADS_DIR") || Path.join(data_dir, "uploads"),
  backups_dir: System.get_env("KAKEMONO_BACKUPS_DIR") || Path.join(data_dir, "backups"),
  api_secret_file: System.get_env("KAKEMONO_API_SECRET_FILE") || Path.join(data_dir, "secret.key")

# Configure your database
config :kakemono, Kakemono.Repo,
  database: database_path,
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  journal_mode: :wal,
  synchronous: :normal,
  cache_size: -64000,
  temp_store: :memory,
  foreign_keys: :on

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :kakemono, KakemonoWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "PlSShy1PwpKUVPuS2kSwpoPY/r0ZaVBmWrYHnuqZt3mtaeVDHDRC6evBSWU/5MeK",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:kakemono, ~w(--bundle --watch)]},
    tailwind: {Tailwind, :install_and_run, [:kakemono, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :kakemono, KakemonoWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/kakemono_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :kakemono, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Path to install SaladUI components
config :salad_ui, components_path: Path.join(File.cwd!(), "lib/kakemono_web/components")
