import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :kakemono, KakemonoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Kakemono.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Behind an HTTPS-terminating reverse proxy: mark the session cookie Secure and
# refuse to let an anonymous visitor set the backend password over the web.
config :kakemono, :secure_cookies, true
config :kakemono, :allow_web_password_setup, false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
